### ISSUE TITLE
Cannot start BFF desktop in development environment (MacOS)

### ISSUE THREAD

**Issue by pgarrison** [AllenInstitute/biofile-finder#364]
# Steps to reproduce
* `git clone ...`
* `npm ci`
* `npm --prefix packages/desktop run start`
  * Expected output: An electron window opens with BFF
  * Actual output: An electron process starts, and "Electron" shows up in the task bar, but there is no window. The terminal logs the following error message ([full log here](https://gist.github.com/pgarrison/5d9cb663c4510862b77b4874a2f1ebba)).
  ```
   An error occurred loading React Dev Tools:  Error: Invalid header: Does not start with Cr24
       at crxToZip (/Users/philip.garrison/workspace/biofile-finder/packages/desktop/dist/main/index.js:59871:15)
       at /Users/philip.garrison/workspace/biofile-finder/packages/desktop/dist/main/index.js:59908:32
       at callHanler (/Users/philip.garrison/workspace/biofile-finder/packages/desktop/dist/main/index.js:62253:16)
       at tryCatcher (/Users/philip.garrison/workspace/biofile-finder/packages/desktop/dist/main/index.js:61970:32)
       at /Users/philip.garrison/workspace/biofile-finder/packages/desktop/dist/main/index.js:62109:38
       at flush (/Users/philip.garrison/workspace/biofile-finder/packages/desktop/dist/main/index.js:62012:17)
       at processTicksAndRejections (node:internal/process/task_queues:78:11)
   ```

# Environment
* Node v16.20.2
* npm 8.19.4
* MacOS Sonoma 14.6
* M1 processor from 2020

# Debugging
* I have no trouble running the production build of BFF 7.0.0 for Mac.
* I have no trouble running BFF web in the same environment.
* I got a suggestion to try removing zarrita and duckDB, but this did not change the behavior.
* The React Dev Tools error message quoted above may not be related. The Cr24 header identifies a Chrome extension, and we cannot install the React Dev Tools Chrome extension for electron. This is a known BFF issue, and other developers get related (but different) React Dev Tools error messages.

**Comment by pgarrison** [comment]
I removed React Dev Tools and that resolved it!
